dependencies:
  flutter:
    sdk: flutter
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  url_launcher: ^6.3.0
  provider: ^6.1.1
  intl: ^0.19.0 # For date formatting

dev_dependencies:
  hive_generator: ^2.0.1
  build_runner: ^2.4.8
